### ISSUE TITLE
Lidando com vetor

### ISSUE THREAD

**Issue by kyriosdata** [vixtorocha/cs-2019-01#11]
A função cpfStringToArray pode ser substituída por `Array(str.length).fill().map((v,i) => parseInt(d[i]))`. Ou ainda, você pode usar a função, mas melhor seria `cpf.push(parseInt(d[i]))`.

**Comment by vixtorocha** [comment]
Resolvido em 32e1d109e0a873cfbbeb9b61df19eb74fb596a7b
