### ISSUE TITLE
Menor escopo, melhor

### ISSUE THREAD

**Issue by kyriosdata** [vixtorocha/cs-2019-01#15]
Em index.js, linha 110, é definida variável que só é usada na linha 117. Esta distância aumenta a quantidade de "carga" em qualquer cérebro, sem benefício algum. Ou seja, defina a variável lá na linha 117. 

Em tempo, não se trata de uma variável, neste caso, mas de uma constante (**const**).

**Comment by vixtorocha** [comment]
Corrigido em 00f8641540f911510f808754263287ff7156b8b9
