### ISSUE TITLE
Não pode ser final nem ter construtor privado

### ISSUE THREAD

**Issue by kyriosdata** [vixtorocha/cs-2019-01#42]
https://github.com/vixtorocha/cs-2019-01/blob/4e3cb986fd36feb002efcdc74632dbeb71e47204/aula-11/src/main/java/com/github/vixtorocha/exemplo/application/api/Application.java#L13

Conforme está o Spring Boot não irá funcionar corretamente. Remova estas orientações equivocadamente, neste caso específico, introduzidas provavelmente pelo PMD.

**Comment by vixtorocha** [comment]
Corrigido.
