### ISSUE TITLE
Spring Boot (final classe e private method)

### ISSUE THREAD

**Issue by kyriosdata** [vixtorocha/cs-2019-01#47]
Remova de todas as classes com referência para o Spring Boot o modificador final e os construtores private. Esta exigência do PMD, suponho, não se aplica a estes casos e impede o funcionamento correto do serviço. Acredito que não tenha testado, pois assim não funciona.

**Comment by vixtorocha** [comment]
Corrigido em 0529bbbba04b3ec55677e0cabcbf424880147a16
