### ISSUE TITLE
Ainda não corrigida a documentação

### ISSUE THREAD

**Issue by kyriosdata** [vixtorocha/cs-2019-01#61]
https://github.com/vixtorocha/cs-2019-01/blob/174f954cfa2376b19fdc10dda82fd2c8b4b16442/aula-11/src/main/java/com/github/vixtorocha/exemplo/domain/Diferenca.java#L12

Antes de fechar as issues, por favor, faça a devida verificação. Já imaginou não cumprir as exigências por um engano como este?

**Comment by vixtorocha** [comment]
Corrigida anteriormente em 143650503f0141d47c5ce5a028b11d757d55d2de
