### ISSUE TITLE
Fechada (por engano)

### ISSUE THREAD

**Issue by kyriosdata** [vixtorocha/cs-2019-01#62]
https://github.com/vixtorocha/cs-2019-01/blob/174f954cfa2376b19fdc10dda82fd2c8b4b16442/aula-11/src/main/java/com/github/vixtorocha/exemplo/application/api/DiferencaController.java#L25

Documentação não está presente, persiste o que já foi identificado anteriormente.

**Comment by vixtorocha** [comment]
Corrigida anteriormente em 143650503f0141d47c5ce5a028b11d757d55d2de
