### ISSUE TITLE
Substituir switch

### ISSUE THREAD

**Issue by kyriosdata** [vixtorocha/cs-2019-01#8]
- Switch das linhas 98 até 123 deve ser repensado. Observe que está sendo obrigado que alguns meses tenha exatamente uma quantidade especificada de dias. A intenção possivelmente era outra (o maior número de dias do mês?). 
- Observe que um vetor, conforme abaixo, poderia eliminar a necessidade do switch. Concorda?
`const numeroMaxDias = [ 0, 31, 28, 31, 30, 31, 30, ......` para o qual numeroMaxDias[mes] retornaria a quantidade máxima de dias do mês em questão. Sem necessidade desse enorme switch.

**Comment by vixtorocha** [comment]
Corrigido em 843679a14bf3fccb914f5e338752d5a8d6d8602e
