### ISSUE TITLE
Possível bug

### ISSUE THREAD

**Issue by kyriosdata** [vixtorocha/cs-2019-01#9]
O trecho de código 
```
    let a;
    for (let i = 0; i < n; i++) {
        if (a[i] != 0) {
            throw new Error("A string deve estar zerada.");
        }
    }
```
define a variável "a" e, logo na sequência, verifica o conteúdo de "a[i]". Para criar um vetor de n posições você deveria usar algo como abaixo, onde todas as entradas contém o valor 0. 
`const vetor = Array(n).fill().map((v,i) => 0);`

**Comment by kyriosdata** [comment]
Este defeito aparecerá com o primeiro teste executado.

**Comment by vixtorocha** [comment]
Corrigido em 7670a57dc818a15eccd91e23a14db4346f1ade9d
